### ISSUE TITLE
Better user interface of buttons and navbar elements

### ISSUE THREAD

**Issue by ChauhanGauri** [Open-Source-Chandigarh/zangetsu#14]
The user interface of previous, next and navbar elements (popular, top movies , login buttons etc.) does not seem like buttons but more like plain text even on hover . I would like to improve that . Please assign me this issue under hacktober fest if applicable . 
![Zangetsu - Google Chrome 10_11_2024 8_15_57 PM](https://github.com/user-attachments/assets/cea292e3-3ecd-43d1-8528-70e1d72ee1ae)

**Comment by Aiyaret-Sandhu** [comment]
This is not a relevant issue. This is a design choice. 
Advice ; Kindly look for another relevant issue.
