### ISSUE TITLE
Improve the Design and Readability of information.md

### ISSUE THREAD

**Issue by varyan03** [Open-Source-Chandigarh/zangetsu#15]
Hi @Aiyaret-Sandhu , I noticed that the current information.md documentation could be improved in terms of design and readability. 
Here are some areas I plan to enhance:

- Improve text formatting (headings, subheadings, bullet points)
- Add consistent styling (e.g., bold/italic for emphasis where necessary)
- Use appropriate markdown features (code blocks, links, etc.) for a better visual hierarchy
- Ensure better readability and structure for users

I would love to take this up under the non-code contributions for Hacktoberfest.

Could you kindly assign this issue to me? Thank you!

**Comment by Aiyaret-Sandhu** [comment]
Alright. you can work on it.

**Comment by varyan03** [comment]
Hello @Aiyaret-Sandhu,I have submitted a PR regarding this issue. Kindly review it, and if it passes all the checks, please merge it.
Thank you!
