### ISSUE TITLE
Too Many imports in APP.JSX.

### ISSUE THREAD

**Issue by AngadSudan** [Open-Source-Chandigarh/zangetsu#2]
ISSUE- There are too many import statements in the APP.JSX which increases the Line of Code(LOC). 

![image](https://github.com/user-attachments/assets/9f56072c-d07a-4c29-a0fd-ed18da8411d8)

Possible Solution- By using a separate INDEX.JSX file which contains all the imported components from pages file.

After adding this update, the code will have better readability and LOC will be reduced.

**Comment by Aiyaret-Sandhu** [comment]
good choice, I have assigned you the issue !
